from __future__ import annotations

from typing import overload, Literal
import sys

import cython
import numpy as _py_np
import numpy.typing as npt

PY3 = sys.version_info[0] > 3

def read(globname: str) -> tuple[npt.NDArray[_py_np.floating], npt.NDArray[_py_np.integer]]:
    ...

def read_off(filename):
    ...

def read_npz(filename):
    ...

def read_gii(filename):
    ...

@cython.boundscheck(False)
def read_stl(filename):
    ...

@overload
def read_obj(filename: str, norm: Literal[False]=False, uv: Literal[False]=False) -> tuple[npt.NDArray[_py_np.floating], npt.NDArray[_py_np.integer]]:
    ...

# TODO: add overloads for all cases
@overload
def read_obj(filename: str, norm: Literal[True], uv: Literal[True]) -> tuple[npt.NDArray[_py_np.floating], npt.NDArray[_py_np.integer], list[list[float]], list[list[float]]]:
    ...

def read_obj(filename: str, norm: bool=False, uv: bool=False) -> tuple[npt.NDArray[_py_np.floating], npt.NDArray[_py_np.integer], list[list[float]] | None, list[list[float]] | None]:
    ...

@cython.boundscheck(False)
def read_vtk(filename):
    ...

def write_vtk(filename, pts: object, polys: object, norms: object=None):
    ...

def write_off(filename, pts: object, polys: object):
    ...

def write_stl(filename, pts: object, polys: object):
    ...

def write_gii(filename, pts: object, polys: object):
    ...

def write_obj(filename, pts: object, polys: object, colors: object=None):
    ...

# This file was generated by stubgen-pyx v0.2.2 from formats.pyx