from __future__ import annotations

import sys

import cython
import numpy as _py_np
import numpy.typing as npt

PY3 = sys.version_info[0] > 3

def read(globname: str) -> tuple[npt.NDArray[_py_np.floating], npt.NDArray[_py_np.integer]]:
    ...

def read_off(filename):
    ...

def read_npz(filename):
    ...

def read_gii(filename):
    ...

@cython.boundscheck(False)
def read_stl(filename):
    ...

def read_obj(filename, norm=False, uv=False):
    ...

@cython.boundscheck(False)
def read_vtk(filename):
    ...

def write_vtk(filename, pts: object, polys: object, norms: object=None):
    ...

def write_off(filename, pts: object, polys: object):
    ...

def write_stl(filename, pts: object, polys: object):
    ...

def write_gii(filename, pts: object, polys: object):
    ...

def write_obj(filename, pts: object, polys: object, colors: object=None):
    ...

# This file was generated by stubgen-pyx v0.2.2 from formats.pyx