from __future__ import annotations

from typing import Optional

import numpy as np
import numpy.typing as npt


class CTMfile:
    filename: bytes
    mode: str
    attribs: dict[int, bytes]
    uvs: dict[int, bytes]

    def __init__(self, filename: bytes, mode: str='r'):
        ...

    def __cinit__(self, filename: bytes, mode: str='r'):
        ...

    def __dealloc__(self):
        ...

    def __len__(self):
        ...

    def setMesh(self, pts: npt.NDArray[np.floating], polys: npt.NDArray[np.integer], norms: Optional[npt.NDArray[np.floating]]=None) -> None:
        ...

    def addAttrib(self, attrib: npt.NDArray[np.floating], name: Optional[str]=None) -> None:
        ...

    def addUV(self, uv: npt.NDArray[np.floating], name: Optional[str]=None, filename: Optional[str]=None) -> None:
        ...

    def getMesh(self) -> tuple[npt.NDArray[np.floating], npt.NDArray[np.integer], None]:
        ...

    def save(self, method='mg2', level: int=9) -> None:
        ...
uvmaps: list[int]
attrmaps: list[int]

def to_bytes(s):
    ...

# This file was generated by stubgen-pyx v0.2.2 from openctm.pyx